apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kproximate.fullname" . }}
  labels:
    {{- include "kproximate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kproximate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kproximate.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kproximate.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "lupinelab/kproximate:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
          - configMapRef:
              name: {{ include "kproximate.fullname" . }}
          - secretRef:
              name: {{ include "kproximate.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In 
                  values:
                  - {{ .Chart.Name }}
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
              topologyKey: kubernetes.io/hostname
      
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists 
          effect: NoSchedule
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
