apiVersion: v1
kind: Secret
metadata:
  name: kproximate-rabbitmq-secret
type: Opaque
data:
  rabbitmq-password: {{ .Values.kproximate.secrets.rabbitmqPassword | b64enc | required ".Values.kproximate.secrets.rabbitmqPassword is required" }}
