apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kproximate.fullname" . }}
type: Opaque
data:
  pmToken: {{ .Values.kproximate.secrets.pmToken | b64enc | required ".Values.kproximate.secrets.pmToken is required" }}
  sshKey: {{ .Values.kproximate.secrets.sshKey | b64enc }}
  rabbitMQPassword: {{ .Values.kproximate.secrets.rabbitmqPassword | b64enc | required ".Values.kproximate.secrets.rabbitmqPassword is required" }}