apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kproximate.fullname" . }}
type: Opaque
data:
  pmToken: {{ .Values.kproximate.pmToken | b64enc | required ".Values.kproximate.pmToken is required" }}
  sshKey: {{ .Values.kproximate.sshKey | b64enc }}
  rabbitMQPassword: {{ .Values.rabbitmq.auth.password | b64enc | required ".Values.rabbitmq.auth.password is required" }}